include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    one_member_abstracts: false
    prefer_relative_imports: true
    always_use_package_imports: false
    always_specify_types: true
    omit_local_variable_types: false
    public_member_api_docs: true
    directives_ordering: true