name: flutter_gutter
description: Get your UI out of the gutter! Ensure all visual gaps between you widgets are consistent, adapted to the
  axis direction, and respond to screen size.
repository: https://github.com/caseycrogers/flutter_gutter

version: 0.1.2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
