name: gutter
description: Ensure all gaps and margins between you widgets are consisten and adapt to screen size!
repository: https://github.com/caseycrogers/gutter

version: 0.1.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
